# Generated by Django 5.2.16 on 2026-08-05 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.JSONField(blank=True, default=list, help_text='De sleutels van de blokken, in de volgorde waarin ze staan. Blokken die hier niet in staan komen achteraan.', verbose_name='Volgorde')),
                ('breedtes', models.JSONField(blank=True, default=dict, help_text='Per blok het aantal kolommen van de twaalf.', verbose_name='Breedtes')),
                ('bijgewerkt', models.DateTimeField(auto_now=True)),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name': 'dashboardindeling',
                'verbose_name_plural': 'dashboardindeling',
                'permissions': (('indelen', 'Mag de dashboardindeling wijzigen'),),
            },
        ),
    ]
